### ISSUE TITLE
[STORY][Prototype] As a passport holder, I want to remove tokens from my stake so that I can unstake on my identity

### ISSUE THREAD

**Issue by gtcsameer** [moonshotcollective/id-staking#11]
Acceptance Criteria:

     Scenario:  User wants to start the unstaking process

GIVEN  I am viewing the homepage of The Staker
AND My wallet has approved token transfers with The Staker app
WHEN When I click the unstake button
THEN my tokens should be unstaked in The Staker app
AND I get a wallet transaction prompt to begin the transaction to retrieve my tokens from The Staker into the original wallet address.

**Comment by brentmartin** [comment]
Acceptance Criteria completed with Demo - but not shown on video

**Comment by farque65** [comment]
Refer to Unstake function in Staking.sol https://github.com/moonshotcollective/id-staking/blob/dev/packages/hardhat/contracts/Staking.sol#L19
