### ISSUE TITLE
[STORY][Prototype] As a passport holder, I want to log into Passport so that I can stamp my staking

### ISSUE THREAD

**Issue by gtcsameer** [moonshotcollective/id-staking#12]
Acceptance Criteria:

     Scenario: User is on Passport and interacts with the prototype stamp with tokens staked in The Staker
GIVEN  I am on the Passport stamps page
WHEN  I interact with The Staker’s associated stamp
THEN   I get stamped

     Scenario: User is on Passport and interacts with the prototype stamp without having any tokens staked in The Staker

GIVEN  I am on the Passport stamps page
WHEN  I interact with The Staker’s associated stamp
THEN   I am prompted to be redirected to The Staker's home page

**Comment by farque65** [comment]
The changes for this story are pushed to the following branch on the Passport Repository https://github.com/gitcoinco/passport/tree/feat-idstaking-integration

**Comment by brentmartin** [comment]
Acceptance Criteria completed with Demo: https://youtu.be/aQYW1hmuH1g
