### ISSUE TITLE
[Research]: Passports can expire Identity Staking Stamps at the end of a Grants round

### ISSUE THREAD

**Issue by farque65** [moonshotcollective/id-staking#4]
THIS IS A DISCOVERY SPIKE

How will expiry date impact passport trust bonus?

- Notes from research on Expiry Date
    - Passport Scorer (trust bonus in this case) considers the creation date on the identity staking stamp. It will take the creation date and add the period for which the staking stamp will be valid.
    - Every time the trust bonus score refreshes it can update the staking period of an identity staking stamp by using the creation date of the stamp.

### Questions to answer

> When calculating Trust Bonus Score for final matching numbers at the end of a round, will they check to see how long a stamp has been in the system? And if so - can they calculate and assign a value based on that time amount?
> 
- 

> When the Grants backend is reading stamps for Trust Bonus Score, do see the date the stamp was created or do they see the date that the stamp was submitted via a passport?
>
-

**Comment by brentmartin** [comment]
@farque65 has coordinated with Passport team to find some solutions
