### ISSUE TITLE
[STORY][Prototype] As a passport holder, I want to approve a staking so that I can send tokens to stake

### ISSUE THREAD

**Issue by gtcsameer** [moonshotcollective/id-staking#6]
Acceptance Criteria:

     Scenario: User wants to start the staking process

GIVEN I am viewing the homepage of The Staker
AND my wallet is connected
WHEN I press the ‘Approve’ button
THEN I see a wallet prompt asking me to allow The Staker to access the necessary token
AND WHEN I sign the wallet message 
THEN I see a transaction success

**Comment by brentmartin** [comment]
Acceptance Criteria completed with Demo: https://youtu.be/aQYW1hmuH1g
