### ISSUE TITLE
[STORY][Prototype] As a passport holder, I want to send tokens to my stake so that I can stake on my identity

### ISSUE THREAD

**Issue by gtcsameer** [moonshotcollective/id-staking#7]
Acceptance Criteria:

     Scenario:  User wants to start the staking process

GIVEN I am viewing the homepage of The Staker
AND My wallet has approved token transfers with The Staker app
WHEN I click the stake button
THEN my tokens should be staked in The Staker app
AND I get confirmation that my tokens are staked in The Staker app
AND I see that my tokens are staked in The Staker app

**Comment by brentmartin** [comment]
Acceptance Criteria completed with Demo: https://youtu.be/aQYW1hmuH1g
