### ISSUE TITLE
[STORY][Prototype] As a passport holder, I want to lock my tokens on my stake so that I can stamp on my identity for a grants round

### ISSUE THREAD

**Issue by gtcsameer** [moonshotcollective/id-staking#8]
Acceptance Criteria:

     Scenario:  User wants to continue the staking process

GIVEN I am viewing the homepage of The Staker
AND I have token(s) staked successfully in The Staker app
WHEN I click the lock tokens button
THEN the tokens in The Staker app should be locked
AND I get visual confirmation that the tokens are locked
AND I see metadata around the locked tokens (how many tokens, how long they are locked for, etc.)
AND I see next steps prompting me towards Passport to claim the associated stamp

**Comment by brentmartin** [comment]
Acceptance Criteria completed with Demo: https://youtu.be/aQYW1hmuH1g

**Comment by farque65** [comment]
Refer Staking.sol stake function - https://github.com/moonshotcollective/id-staking/blob/dev/packages/hardhat/contracts/IDStaking.sol#L92
