### ISSUE TITLE
[STORY][Prototype] As a passport holder, I want my tokens to unlock at the end of a grants round so that I can access my own tokens from my staking

### ISSUE THREAD

**Issue by gtcsameer** [moonshotcollective/id-staking#9]
Acceptance Criteria:

     Scenario:  User wants to continue with the staking process

GIVEN I am viewing the homepage of The Staker
AND I have token(s) staked successfully in The Staker app 
WHEN The given time period has expired
THEN The tokens in The Staker app should be unlocked
AND I get visual confirmation that the tokens are unlocked

**Comment by brentmartin** [comment]
@farque65 will confirm by moving funds back to wallet from prototype - will complete AC

**Comment by farque65** [comment]
Refer to unstake modifier in Staking.sol - https://github.com/moonshotcollective/id-staking/blob/dev/packages/hardhat/contracts/IDStaking.sol#L54

**Comment by farque65** [comment]
After round completed on August 7th I was able to unstake my GTC staked on another user

![Image](https://user-images.githubusercontent.com/8276680/183471522-147a0717-4472-4773-a702-32e3b81fc74d.png)
